services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 80:80
    depends_on:
      - redis
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
